metadataPackage_1524358100300/objects/Barcode__c.object
<CustomObject>
    <label>バーコード</label>
    <nameField>
        <displayFormat>FBY-{00000000}</displayFormat>
        <label>コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadataPackage_1524358100300/objects/BarcodeAssignment__c.object
<CustomObject>
    <label>バーコード関連</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>バーコード関連 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>barcode__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>バーコード</label>
        <referenceTo>Barcode__c</referenceTo>
        <relationshipLabel>バーコード関連</relationshipLabel>
        <relationshipName>barcode_assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/BarcodeAssignment__c/fields/inventory_move_line__c.field-meta.xml
<CustomField>
    <fullName>inventory_move_line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>在庫移動明細</label>
    <referenceTo>InventoryMoveLine__c</referenceTo>
    <relationshipLabel>バーコード関連付</relationshipLabel>
    <relationshipName>barcode_assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

metadataPackage_1524358100300/objects/CurrentInventory__c.object
<CustomObject>
    <label>現在庫</label>
    <nameField>
        <displayFormat>CIV-{00000000}</displayFormat>
        <label>現在庫名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>JAN_code__c</fullName>
        <externalId>true</externalId>
        <label>JANコード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>physical_quantity__c</fullName>
        <label>物理的数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>product_name__c</fullName>
        <label>商品名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>unique_key__c</fullName>
        <formula>warehouse__r.Id &amp;":"&amp;  food_type_lOne__r.Id &amp;":"&amp;  food_type_lTwo__r.Id &amp;":"&amp;  JAN_code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>unique_key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>warehouse__c</fullName>
        <label>倉庫</label>
        <referenceTo>Warehouse__c</referenceTo>
        <relationshipLabel>現在庫</relationshipLabel>
        <relationshipName>current_inventories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/objects/CurrentInventory__c/fields/food_type_l1__c.field-meta.xml
<CustomField>
    <fullName>food_type_l1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>食品分類 (L1)</label>
    <referenceTo>FoodTypeL1__c</referenceTo>
    <relationshipLabel>現在庫</relationshipLabel>
    <relationshipName>food_type_l1ss</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CurrentInventory__c/fields/food_type_l2__c.field-meta.xml
<CustomField>
    <fullName>food_type_l2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>食品分類 (L2)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.food_type_l1__c</field>
            <operation>equals</operation>
            <valueField>FoodTypeL2__c.food_type_l1__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FoodTypeL2__c</referenceTo>
    <relationshipLabel>現在庫</relationshipLabel>
    <relationshipName>food_type_l2ss</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

metadataPackage_1524358100300/objects/InventoryMove__c.object
<CustomObject>
    <label>在庫移動</label>
    <nameField>
        <displayFormat>IVM-{000000}</displayFormat>
        <label>在庫移動名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>completion_time__c</fullName>
        <label>完了時刻</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>transfer_to_warehouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>移動先倉庫</label>
        <referenceTo>Warehouse__c</referenceTo>
        <relationshipLabel>入庫履歴</relationshipLabel>
        <relationshipName>inventory_moves_to</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>inbound</fullName>
        <active>true</active>
        <label>入庫</label>
    </recordTypes>
    <recordTypes>
        <fullName>outbound</fullName>
        <active>true</active>
        <label>出庫</label>
    </recordTypes>
    <recordTypes>
        <fullName>transfer</fullName>
        <active>true</active>
        <label>倉庫間移動</label>
    </recordTypes>
</CustomObject>

metadataPackage_1524358100300/objects/InventoryMoveLine__c.object
<CustomObject>
    <label>在庫移動明細</label>
    <nameField>
        <displayFormat>INVML-{0000000000}</displayFormat>
        <label>在庫移動明細名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>barcode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FBYコード</label>
        <referenceTo>Barcode__c</referenceTo>
        <relationshipLabel>在庫移動明細</relationshipLabel>
        <relationshipName>inventory_move_lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inventory_move__c</fullName>
        <label>在庫移動</label>
        <referenceTo>InventoryMove__c</referenceTo>
        <relationshipLabel>在庫移動明細</relationshipLabel>
        <relationshipName>inventory_move_lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>jan_code__c</fullName>
        <label>JANコード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>quantity_per_unit__c</fullName>
        <defaultValue>1</defaultValue>
        <label>入数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/objects/InventoryMoveLine__c/fields/food_type_l1__c.field-meta.xml
<CustomField>
    <fullName>food_type_l1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>食品分類 (L1)</label>
    <referenceTo>FoodTypeL1__c</referenceTo>
    <relationshipLabel>在庫移動明細</relationshipLabel>
    <relationshipName>food_type_l1s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InventoryMoveLine__c/fields/food_type_l2__c.field-meta.xml
<CustomField>
    <fullName>food_type_l2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>食品分類 (L2)</label>
    <referenceTo>FoodTypeL2__c</referenceTo>
    <relationshipLabel>在庫移動明細</relationshipLabel>
    <relationshipName>food_type_l2s</relationshipName>
    <type>Lookup</type>
</CustomField>

metadataPackage_1524358100300/objects/Warehouse__c.object
<CustomObject>
    <label>倉庫</label>
    <nameField>
        <label>倉庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InventoryMoveWrapper.cls
/**
    InventoryMoveは直接操作することはしない。
    必ず、InventoryMoveManager と InventoryMoveWrapperを使って操作をする。
    Transactionを使うので、データの整合性が担保される。
*/

public with sharing class InventoryMoveWrapper {

    private InventoryMove__c record {get;set;}
    private List<InventoryMoveLineWrapper> lines{get;set;}



    public static final Integer INBOUND  = 0;
    public static final Integer OUTBOUND = 1;
    public static final Integer TRANSFER = 2;
    public static final Integer DISPOSE  = 3;



    public InventoryMoveWrapper( InventoryMove__c record, Integer moveType ) {
        this.record = record;
        this.record.recordTypeId = getRecordTypeId(moveType);
    }

    public InventoryMove__c getRecord(){
        return this.record;
    }

    public void setLines( List<InventoryMoveLineWrapper> lines ){
        this.lines = lines;
    }

    public List<InventoryMoveLineWrapper> getLines(){
        return this.lines;
    }



    /**
        InventoryMoveを保存して必要なトランザクションを実行します。
    */
    public void confirmInventoryMove(){

        // STEP 1 Begin transaction
        Savepoint sp = Database.setSavepoint();

        try{

        // STEP 2 Lock the related CurrentInventory, CurrentInventoryLine and related Barcode records
            // get CurrentInventory lines
            Set<String> uniqueKeys = new Set<String>();
            Map<String, CurrentInventory__c> mapCurrentInventory = new Map<String, CurrentInventory__c>();

            for( InventoryMoveLineWrapper line:this.getLines() ){

                String uniqueKey =
                    String.ValueOf(this.getRecord().transfer_to_warehouse__c).left(15) + ':' +
                    String.ValueOf(line.getRecord().food_type_l1__c)         .left(15) + ':' +
                    String.ValueOf(line.getRecord().food_type_l2__c)         .left(15) + ':' +
                    line.getRecord().jan_code__c;
                uniqueKeys.add(uniqueKey);
            }
            System.debug( uniqueKeys );


            for( CurrentInventory__c ci:[SELECT Id, physical_quantity__c, unique_key__c FROM CurrentInventory__c WHERE unique_key__c IN :uniqueKeys ] ){
                mapCurrentInventory.put( ci.unique_key__c, ci );
            }
            for( String uniqueKey:uniqueKeys ){
                if( !mapCurrentInventory.containsKey( uniqueKey ) ){
                    CurrentInventory__c ci = new CurrentInventory__c();
                    List<String> ids = uniqueKey.split(':');
                    // ci.product_name__c = TODO put in the product name
                    ci.warehouse__c    = ids[0];
                    ci.food_type_l1__c = ids[1];
                    ci.food_type_l2__c = ids[2];
                    ci.jan_code__c     = ids[3];
                    ci.physical_quantity__c = 0;
                    mapCurrentInventory.put( uniqueKey, ci );
                }
            }




        // STEP 3 Update the locked records
        this.getRecord().completion_time__c = Datetime.now();
        UPSERT this.getRecord();

        List<InventoryMoveLine__c> imls = new List<InventoryMoveLine__c>();
        List<BarcodeAssignment__c> bas = new List<BarcodeAssignment__c>();

        for( InventoryMoveLineWrapper line:this.getLines() ){
            line.getRecord().inventory_move__c = this.getRecord().Id;
            imls.add( line.getRecord() );
        }
        UPSERT imls;

        for( InventoryMoveLineWrapper line:this.getLines() ){

            String uniqueKey =
                String.ValueOf(this.getRecord().transfer_to_warehouse__c).left(15) + ':' +
                String.ValueOf(line.getRecord().food_type_l1__c)         .left(15) + ':' +
                String.ValueOf(line.getRecord().food_type_l2__c)         .left(15) + ':' +
                line.getRecord().jan_code__c;

            for( Barcode__c barcode:line.barcodes ){
                BarcodeAssignment__c ba = new BarcodeAssignment__c();
                ba.inventory_move_line__c = line.getRecord().Id;
                ba.barcode__c = barcode.Id;
                bas.add(ba);

                mapCurrentInventory.get( uniqueKey ).physical_quantity__c += line.getRecord().quantity_per_unit__c;

            }
        }
        UPSERT bas;

        UPSERT mapCurrentInventory.values();

        // STEP 4 Commit

        }
        catch( Exception e ){
            Database.rollback(sp);
            throw new AppException( e.getMessage() );
        }



    }

    public void cancelInventoryMove(){

    }

    public void saveInventoryMove(){

    }



    private static String getRecordTypeId( Integer moveType ){
        String tmpRecordTypeId = null;
        if( moveType == InventoryMoveWrapper.INBOUND ){
            tmpRecordTypeId = Schema.SObjectType.InventoryMove__c.getRecordTypeInfosByName().get('入庫').getRecordTypeId();
        }
        else if( moveType == InventoryMoveWrapper.OUTBOUND ){
            tmpRecordTypeId = Schema.SObjectType.InventoryMove__c.getRecordTypeInfosByName().get('出庫').getRecordTypeId();
        }
        else if( moveType == InventoryMoveWrapper.TRANSFER ){
            tmpRecordTypeId = Schema.SObjectType.InventoryMove__c.getRecordTypeInfosByName().get('倉庫間移動').getRecordTypeId();
        }
        else if( moveType == InventoryMoveWrapper.DISPOSE ){
            tmpRecordTypeId = Schema.SObjectType.InventoryMove__c.getRecordTypeInfosByName().get('廃棄').getRecordTypeId();
        }
        if( String.isEmpty(tmpRecordTypeId) ) throw new AppException('invalid record type');

        return tmpRecordTypeId;
    }
}