metadataPackage_1524358100300/objects/Barcode__c.object
<CustomObject>
    <label>バーコード</label>
    <nameField>
        <displayFormat>FBY-{00000000}</displayFormat>
        <label>コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadataPackage_1524358100300/objects/CurrentInventory__c.object
<CustomObject>
    <label>現在庫</label>
    <nameField>
        <displayFormat>CIV-{00000000}</displayFormat>
        <label>現在庫名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>JAN_code__c</fullName>
        <externalId>true</externalId>
        <label>JANコード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>product_name__c</fullName>
        <label>商品名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>warehouse__c</fullName>
        <label>倉庫</label>
        <referenceTo>Warehouse__c</referenceTo>
        <relationshipLabel>現在庫</relationshipLabel>
        <relationshipName>current_inventories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/objects/CurrentInventory__c/fields/food_type_l1__c.field-meta.xml
<CustomField>
    <fullName>food_type_l1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>食品分類 (L1)</label>
    <referenceTo>FoodTypeL1__c</referenceTo>
    <relationshipLabel>現在庫</relationshipLabel>
    <relationshipName>food_type_l1ss</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CurrentInventory__c/fields/food_type_l2__c.field-meta.xml
<CustomField>
    <fullName>food_type_l2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>食品分類 (L2)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.food_type_l1__c</field>
            <operation>equals</operation>
            <valueField>FoodTypeL2__c.food_type_l1__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FoodTypeL2__c</referenceTo>
    <relationshipLabel>現在庫</relationshipLabel>
    <relationshipName>food_type_l2ss</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

metadataPackage_1524358100300/objects/InventoryMoveLine__c.object
<CustomObject>
    <label>在庫移動明細</label>
    <nameField>
        <displayFormat>INVML-{0000000000}</displayFormat>
        <label>在庫移動明細名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>barcode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FBYコード</label>
        <referenceTo>Barcode__c</referenceTo>
        <relationshipLabel>在庫移動明細</relationshipLabel>
        <relationshipName>inventory_move_lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>food_name__c</fullName>
        <label>食品名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>jan_code__c</fullName>
        <label>JANコード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>price__c</fullName>
        <label>価格</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

force-app/main/default/objects/InventoryMoveLine__c/fields/food_type_l1__c.field-meta.xml
<CustomField>
    <fullName>food_type_l1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>食品分類 (L1)</label>
    <referenceTo>FoodTypeL1__c</referenceTo>
    <relationshipLabel>在庫移動明細</relationshipLabel>
    <relationshipName>food_type_l1s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InventoryMoveLine__c/fields/food_type_l2__c.field-meta.xml
<CustomField>
    <fullName>food_type_l2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>食品分類 (L2)</label>
    <referenceTo>FoodTypeL2__c</referenceTo>
    <relationshipLabel>在庫移動明細</relationshipLabel>
    <relationshipName>food_type_l2s</relationshipName>
    <type>Lookup</type>
</CustomField>

metadataPackage_1524358100300/objects/Warehouse__c.object
<CustomObject>
    <label>倉庫</label>
    <nameField>
        <label>倉庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InventoryMoveLineWrapper.cls
public class InventoryMoveLineWrapper {
    private InventoryMoveLine__c record {get;set;}
    public JanProduct janProduct {get;set;}
    public List<Barcode__c> barcodes {get;set;}



    public InventoryMoveLine__c getRecord(){
        return this.record;
    }


    public InventoryMoveLineWrapper( InventoryMoveLine__c iml ) {
        this.record = iml;
        this.barcodes = new List<Barcode__c>();
    }
    public InventoryMoveLineWrapper( String warehouseId, JanProduct janProduct ) {
        this.record = new InventoryMoveLine__c();
        this.record.jan_code__c = janProduct.janCode;
        this.record.food_name__c = janProduct.name;
        this.record.price__c = janProduct.price;

        // see if this jan code already exists
        CurrentInventory__c ci = [
            SELECT Id, jan_code__c, food_type_l1__c, food_type_l2__c,product_name__c
            FROM CurrentInventory__c
            WHERE
                jan_code__c =: janProduct.janCode AND warehouse__c =: warehouseId
            ORDER BY LasTModifiedDate DESC LIMIT 1
        ];

        if( ci == null ){
            ci = [
                SELECT Id, jan_code__c, food_type_l1__c, food_type_l2__c,product_name__c
                FROM CurrentInventory__c
                WHERE
                    jan_code__c =: janProduct.janCode
                ORDER BY LasTModifiedDate DESC LIMIT 1
            ];
        }

        if( ci != null ){
            this.record.food_type_l1__c = ci.food_type_l1__c;
            this.record.food_type_l2__c = ci.food_type_l2__c;
        }





        this.janProduct = janProduct;
    }
}