metadataPackage_1524358100300/objects/Barcode__c.object
<CustomObject>
    <label>バーコード</label>
    <nameField>
        <displayFormat>FBY-{00000000}</displayFormat>
        <label>コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>current_inventory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>現在庫</label>
        <referenceTo>CurrentInventory__c</referenceTo>
        <relationshipLabel>バーコード</relationshipLabel>
        <relationshipName>barcodes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>expiration_date__c</fullName>
        <label>賞味期限</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>remaining_quantity__c</fullName>
        <formula>original_quantity__c -  shipped_quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>残数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

metadataPackage_1524358100300/objects/CurrentInventory__c.object
<CustomObject>
    <label>現在庫</label>
    <nameField>
        <displayFormat>CIV-{00000000}</displayFormat>
        <label>現在庫名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>product_name__c</fullName>
        <label>商品名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>warehouse__c</fullName>
        <label>倉庫</label>
        <referenceTo>Warehouse__c</referenceTo>
        <relationshipLabel>現在庫</relationshipLabel>
        <relationshipName>current_inventories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

metadataPackage_1524358100300/objects/InventoryMove__c.object
<CustomObject>
    <label>在庫移動</label>
    <nameField>
        <displayFormat>IVM-{000000}</displayFormat>
        <label>在庫移動名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>transfer_from_warehouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>移動元倉庫</label>
        <referenceTo>Warehouse__c</referenceTo>
        <relationshipLabel>出庫履歴</relationshipLabel>
        <relationshipName>inventory_moves_from</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>transfer_to_warehouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>移動先倉庫</label>
        <referenceTo>Warehouse__c</referenceTo>
        <relationshipLabel>入庫履歴</relationshipLabel>
        <relationshipName>inventory_moves_to</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>transfer</fullName>
        <active>true</active>
        <label>倉庫間移動</label>
    </recordTypes>
</CustomObject>

metadataPackage_1524358100300/objects/InventoryMoveLineOutbound__c.object
<CustomObject>
    <label>在庫移動明細 (出庫)</label>
    <nameField>
        <displayFormat>IMLO-{0000000}</displayFormat>
        <label>在庫移動明細 (出庫) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>barcode__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>バーコード</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Barcode__c.current_inventory__r.Id</field>
                <operation>notEqual</operation>
                <value/>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Barcode__c</referenceTo>
        <relationshipLabel>在庫移動明細 (出庫)</relationshipLabel>
        <relationshipName>inventory_move_line_outbounds</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1524358100300/objects/Warehouse__c.object
<CustomObject>
    <label>倉庫</label>
    <nameField>
        <label>倉庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/controllers/TransferController.cls
global with sharing class TransferController {

  public List<Warehouse__c> warehouses1 {get;set;}
  public String warehouses_s {get;set;}
  public String selectedWarehouseId {get;set;}

  global TransferController() {

      selectedWarehouseId = null;
      // try to figure out the last warehouse he made deposit to
      List<InventoryMove__c> transfers = [
          SELECT transfer_to_warehouse__c
          FROM InventoryMove__c
          WHERE
              CreatedById =:UserInfo.getUserId() AND
              recordTypeId =: InventoryMoveWrapper.getRecordTypeId(InventoryMoveWrapper.TRANSFER) AND
              transfer_to_warehouse__c != NULL
          ORDER BY CreatedDate DESC
          LIMIT 1
      ];

      if ( transfers.size() > 0 ) {
          selectedWarehouseId = String.valueOf( transfers[0].transfer_to_warehouse__c );
      }

      warehouses1 = [SELECT Id, Name FROM Warehouse__c];
      warehouses_s = JSON.serialize( warehouses1 );

  }

  @RemoteAction
  global static Object findBarcode( String barcode ){
    List<Barcode__c> barcodes = [SELECT Id, Name, current_inventory__r.warehouse__r.Name, current_inventory__r.product_name__c, remaining_quantity__c, expiration_date__c FROM Barcode__c WHERE Name =: barcode LIMIT 1];
    if( barcodes.size() > 0 ){
      return barcodes[0];
    }
    else{
      return null;
    }

  }

  @RemoteAction
  global static Object saveTransferBarcodeMove( String jsonStr ){
    // 倉庫 Idの確認
    //Map<String, Object> jsonObj = (Map<String, Object>) JSON.deserializeUntyped(jsonStr);
    List<Object> barcodeList = (List<Object>) JSON.deserializeUntyped(jsonStr);
    for(Object recordObj : barcodeList){
      Map<String, Object> record = (Map<String, Object>) recordObj;
      InventoryMoveWrapper imw = InventoryManager.createInventoryMoveWrapper(InventoryMoveWrapper.TRANSFER);
      imw.getRecord().transfer_from_warehouse__c  = (Id)record.get('fromWarehouseId'); // 移動元の倉庫のID
      imw.getRecord().transfer_to_warehouse__c    = (Id)record.get('toWarehouseId'); // 移動先の倉庫のID
      InventoryMoveLineOutboundWrapper transferLine = new InventoryMoveLineOutboundWrapper( new InventoryMoveLineOutbound__c() );
      transferLine.getRecord().barcode__c = (Id)record.get('Id'); // 移動させるバーコードのID
      imw.addInventoryMoveLineOutboundWrapper( transferLine );
      imw.confirmInventoryMove();
    }
    return true;
  }

  @RemoteAction
  global static List<Warehouse__c> getWarehouse(){
    return [SELECT Id, Name FROM Warehouse__c];
  }

}