metadataPackage_1524358100300/objects/Barcode__c.object
<CustomObject>
    <label>バーコード</label>
    <nameField>
        <displayFormat>FBY-{00000000}</displayFormat>
        <label>コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>current_inventory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>現在庫</label>
        <referenceTo>CurrentInventory__c</referenceTo>
        <relationshipLabel>バーコード</relationshipLabel>
        <relationshipName>barcodes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>expiration_date__c</fullName>
        <label>賞味期限</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>remaining_quantity__c</fullName>
        <formula>original_quantity__c -  shipped_quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>残数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>shipped_quantity__c</fullName>
        <label>出庫数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

metadataPackage_1524358100300/objects/CurrentInventory__c.object
<CustomObject>
    <label>現在庫</label>
    <nameField>
        <displayFormat>CIV-{00000000}</displayFormat>
        <label>現在庫名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>food_type_lOne__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>食品分類 (L1)</label>
        <referenceTo>FoodTypeLOne__c</referenceTo>
        <relationshipLabel>現在庫</relationshipLabel>
        <relationshipName>food_type_l1ss</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>product_name__c</fullName>
        <label>商品名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>warehouse__c</fullName>
        <label>倉庫</label>
        <referenceTo>Warehouse__c</referenceTo>
        <relationshipLabel>現在庫</relationshipLabel>
        <relationshipName>current_inventories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

metadataPackage_1524358100300/objects/FoodTypeLOne__c.object
<CustomObject>
    <label>食品分類 (L1)</label>
    <nameField>
        <label>食品分類 Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadataPackage_1524358100300/objects/FoodTypeLTwo__c.object
<CustomObject>
    <label>食品分類 (L2)</label>
    <nameField>
        <label>食品分類 (L2) Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>food_type_lOne__c</fullName>
        <label>食品分類 (L1)</label>
        <referenceTo>FoodTypeLOne__c</referenceTo>
        <relationshipLabel>食品分類 (L2)</relationshipLabel>
        <relationshipName>food_type_lTwos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

metadataPackage_1524358100300/objects/InventoryMoveLineOutbound__c.object
<CustomObject>
    <label>在庫移動明細 (出庫)</label>
    <nameField>
        <displayFormat>IMLO-{0000000}</displayFormat>
        <label>在庫移動明細 (出庫) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>barcode__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>バーコード</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Barcode__c.current_inventory__r.Id</field>
                <operation>notEqual</operation>
                <value/>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Barcode__c</referenceTo>
        <relationshipLabel>在庫移動明細 (出庫)</relationshipLabel>
        <relationshipName>inventory_move_line_outbounds</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>outbound_quantity__c</fullName>
        <label>出庫数</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

metadataPackage_1524358100300/objects/Warehouse__c.object
<CustomObject>
    <label>倉庫</label>
    <nameField>
        <label>倉庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadataPackage_1524358100300/classes/OutboundController.cls
global with sharing class OutboundController {
  global OutboundController() {

  }

  @RemoteAction
  global static Object findBarcode( String barcode ){
    List<Barcode__c> barcodes = [SELECT Id, Name, current_inventory__r.warehouse__r.Name, current_inventory__r.product_name__c, remaining_quantity__c, expiration_date__c FROM Barcode__c WHERE Name =: barcode LIMIT 1];
    if( barcodes.size() > 0 ){
      return barcodes[0];
    }
    else{
      return null;
    }

  }

  @RemoteAction
  global static Object saveOutboundBarcodeMove( String jsonStr ){
    // 倉庫 Id、商品 ID の確認
    // TODO fix this to be dynamic
    //Map<String, Object> jsonObj = (Map<String, Object>) JSON.deserializeUntyped(jsonStr);
    List<Object> barcodeList = (List<Object>) JSON.deserializeUntyped(jsonStr);
    for(Object recordObj : barcodeList){
      Map<String, Object> record = (Map<String, Object>) recordObj;
      InventoryMoveWrapper imw = InventoryManager.createInventoryMoveWrapper( InventoryMoveWrapper.OUTBOUND );
      imw.getRecord().transfer_from_warehouse__c = (Id)record.get('warehouseId');
      InventoryMoveLineOutboundWrapper outboundLine = new InventoryMoveLineOutboundWrapper( new InventoryMoveLineOutbound__c() );
      outboundLine.getRecord().barcode__c = (Id)record.get('Id');
      outboundLine.getRecord().outbound_quantity__c = (decimal)record.get('shipped_quantity__c');
      imw.addInventoryMoveLineOutboundWrapper( outboundLine );
      imw.confirmInventoryMove();
    }

    return true;
  }

  @RemoteAction
  global static List<FoodTypeLOne__c> getFoodTypeLOne(){
    return [SELECT Id, Name FROM FoodTypeLOne__c];
  }

  @RemoteAction
  global static List<FoodTypeLTwo__c> getFoodTypeLTwo( String foodTypeLOneId ){
    return [SELECT Id, Name FROM FoodTypeLTwo__c WHERE food_type_lOne__c = :foodTypeLOneId];
  }

}